trigger:
  - main  # Runs pipeline on push to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Uses Ubuntu VM for the build process

steps:
  # Install Node.js 18 (Matches Azure App Service runtime)
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js 18 LTS'

  # Install dependencies and build (if applicable)
  - script: |
      npm install
      npm run build  # Remove if your backend does not require building
    displayName: 'Install Dependencies & Build'

  # Deploy to Azure Web App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'AzureServiceConnection-bytepantry'  # Your Azure Subscription ID
      appName: 'bytepantry-api'  # Name of your Azure App Service
      package: '.'  # Deploys the entire backend folder
      runtimeStack: 'NODE|18-lts'  # Matches App Service runtime
    displayName: 'Deploy to Azure Web App'
